- name: update homebrew itself
  homebrew:
    update_homebrew: true

- name: install brew packages
  homebrew:
    state: latest
    name:
      - aqua
      - fish
      - git
      - imagemagick
      - latexindent
      - make
      - mas
      - pandoc
      - rgbds
      - rust
      - tig
      - tmux
      - wget
