- name: install brew cask packages
  homebrew_cask:
    state: latest
    name:
      - 1password
      - android-studio
      - aquaskk
      - claude
      - docker-desktop
      - font-plemol-jp-nf
      - gcloud-cli
      - ghostty
      - google-chrome
      - karabiner-elements
      - keycastr
      - mactex
      - microsoft-office
      - numi
      - raycast
      - skim
      - tableplus
      - tailscale-app
      - whisky
      - zoom
      - zotero
