- name: install brew cask packages
  homebrew_cask:
    state: latest
    name:
      - 1password
      - aquaskk
      - claude
      - cursor
      - docker-desktop
      - font-plemol-jp-nf
      - gcloud-cli
      - ghostty
      - karabiner-elements
      - numi
      - raycast
      - tableplus
      - zoom
