- name: check installed claude plugins
  shell: claude plugin marketplace list
  register: claude

- name: install claude plugins
  shell: claude plugin marketplace add affaan-m/everything-claude-code
  when: "'everything-claude-code' not in claude.stdout"
  tags: claude
