- name: create directory
  file:
    state: directory
    path: ~/{{ item }}
    mode: 0700
  loop:
    - .codex
    - .config/aquaproj-aqua
    - .config/fish/conf.d
    - .config/fish/functions
    - .config/ghostty
    - .config/karabiner/assets
    - .config/nvim
    - .local/share
    - .ssh
    - Library/Application Support/lazygit
    - bin

- name: link files
  file:
    state: link
    src: "{{ playbook_dir }}/../{{ item.src }}"
    dest: ~/{{ item.dest }}
    force: true
    follow: false
  loop:
    - src: .config/aquaproj-aqua/aqua.yaml
      dest: .config/aquaproj-aqua/aqua.yaml
    - src: .config/fish/config.fish
      dest: .config/fish/config.fish
    - src: .config/fish/conf.d/tide.fish
      dest: .config/fish/conf.d/tide.fish
    - src: .config/fish/functions/fish_user_key_bindings.fish
      dest: .config/fish/functions/fish_user_key_bindings.fish
    - src: .config/fish/functions/fzf_change_directory.fish
      dest: .config/fish/functions/fzf_change_directory.fish
    - src: .config/ghostty/config
      dest: .config/ghostty/config
    - src: .config/hub
      dest: .config/hub
    - src: .config/karabiner
      dest: .config/karabiner/assets/complex_modifications
    - src: .config/lazygit/config.yml
      dest: Library/Application Support/lazygit/config.yml
    - src: .config/nvim/init.lua
      dest: .config/nvim/init.lua
    - src: .config/nvim/lua
      dest: .config/nvim/lua
    - src: .config/tmux
      dest: .config/tmux
    - src: .czrc
      dest: .czrc
    - src: .gitconfig
      dest: .gitconfig
    - src: .gitignore
      dest: .gitignore
    - src: .latexmkrc
      dest: .latexmkrc
    - src: .npmrc
      dest: .npmrc
    - src: .scripts/ide
      dest: bin/ide
    - src: .ssh/config
      dest: .ssh/config
