- name: install npm packages
  npm:
    state: latest
    global: true
    name: "{{ item }}"
  loop:
    - "@anthropic-ai/claude-code"
    - "@github/copilot"
    - "@google/gemini-cli"
    - "@openai/codex"
    - commitizen
    - cz-git
    - npm-check-updates
    - prettier
