- name: install npm packages
  npm:
    state: latest
    global: true
    name: "{{ item }}"
  loop:
    - "@google/gemini-cli"
    - commitizen
    - cz-git
    - npm-check-updates
    - oxfmt
    - oxlint
    - prettier
